### ISSUE TITLE
How is the line graph in the bottom right corner of the readme picture drawn/generated?

### ISSUE THREAD

**Issue by jmataraz** [zeux/microprofile#13]
Is that picture in the README from a captured html snapshot, or a live in-app UI view? How was it built, and then how do you enable it to be shown in the detailed view, if that's required?

**Comment by zeux** [comment]
This is from the live view (web view doesn't support it I think), and you can add/remove individual scopes to that graph by left clicking the bar in the detailed view. See calls to MicroProfileToggleGraph in microprofileui.h.
